export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Learn Code",
  headline: "Top Problem Bank",
  description: "Get access to the most commonly asked interview problems",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../public/images/computer.svg"),
  alt: "img",
  dark: true,
  primary: true,
  darkText: false,
};
